import { applyCalculatedFields } from "./calculations";
import { defaultDocumentTypeCodes } from "./nomenclature";
import type {
  CustomColumn,
  Dependency,
  DocumentTypeCode,
  ManufacturingComponent,
  PlannerState,
  Product,
  Scenario,
  Station,
  Task,
  Zone,
} from "./types";

const BASE_TIME = "2026-05-07T07:00:00.000-07:00";
const baseMs = Date.parse(BASE_TIME);

function timeAt(minutes: number) {
  return new Date(baseMs + minutes * 60_000).toISOString();
}

const product: Product = {
  id: "prod-sdg125-hybrid",
  productCode: "FB-V2",
  name: "SDG125-to-Hybrid Generator Conversion",
  sku: "SDG125-HYB",
  family: "Generator Conversion",
  revision: "Rev A",
  description: "Convert a donor SDG125 generator into a hybrid generator configuration.",
  ownerName: "Manufacturing Engineering",
  status: "draft",
  targetManHours: 140,
  demandQuantity: 1,
  demandPeriod: "day",
  grossAvailableMinutes: 540,
  breakMinutes: 30,
  lunchMinutes: 60,
  meetingMinutes: 15,
  plannedDowntimeMinutes: 15,
  workDaysPerWeek: 5,
  workWeeksPerMonth: 4.33,
  availableWorkDaysPerMonth: 21.65,
  netAvailableMinutes: 450,
  weeklyAvailableMinutes: 2250,
  monthlyAvailableMinutes: 9742.5,
  calculatedTaktMinutes: 450,
  activeTaktMinutes: 450,
  createdAt: "2026-05-07T07:00:00.000-07:00",
  updatedAt: "2026-05-07T07:30:00.000-07:00",
};

const scenario: Scenario = {
  id: "scenario-current-state",
  productId: product.id,
  name: "Current State Disassembly Lane",
  description: "First line-development model for one-piece-flow donor teardown and hybrid prep.",
  type: "current_state",
  status: "draft",
  targetOutput: 1,
  targetOutputPeriod: "day",
  notes: "Seeded from the root manufacturing line Gantt app spec.",
  createdAt: product.createdAt,
  updatedAt: product.updatedAt,
};

const stations: Station[] = [
  {
    id: "station-fluid-loto",
    scenarioId: scenario.id,
    sequence: 1,
    name: "Fluid Drain, LOTO & Safe Teardown Prep",
    description: "Make the SDG125 safe before deeper disassembly.",
    ownerName: "Safety / Teardown Lead",
    plannedCycleMinutes: 0,
    plannedOperators: 1,
    plannedManHours: 0,
    taktStatus: "missing",
    bottleneckFlag: false,
    wipLimit: 1,
    area: "Disassembly",
    toolsRequired: ["LOTO kit", "drain pans", "caps and plugs"],
    safetyNotes: "Zero-energy check and fluid control must be complete before release.",
    qcNotes: "Traveler signoff required.",
  },
  {
    id: "station-electrical-recovery",
    scenarioId: scenario.id,
    sequence: 2,
    name: "Electrical Disconnect, Labeling & Control Cabinet Recovery",
    description: "Recover controls while preserving wiring knowledge and routing.",
    ownerName: "Electrical Lead",
    plannedCycleMinutes: 0,
    plannedOperators: 2,
    plannedManHours: 0,
    taktStatus: "missing",
    bottleneckFlag: false,
    wipLimit: 1,
    area: "Disassembly",
    toolsRequired: ["label printer", "camera", "terminal tools"],
    safetyNotes: "Confirm LOTO and zero-energy status before disconnect.",
    qcNotes: "Open connectors protected and labels legible.",
  },
  {
    id: "station-cooling-removal",
    scenarioId: scenario.id,
    sequence: 3,
    name: "Cooling, Aftertreatment & Accessory Removal",
    description: "Remove bulky support systems before engine and alternator module removal.",
    ownerName: "Mechanical Lead",
    plannedCycleMinutes: 0,
    plannedOperators: 2,
    plannedManHours: 0,
    taktStatus: "missing",
    bottleneckFlag: false,
    wipLimit: 1,
    area: "Disassembly",
    toolsRequired: ["hose caps", "guard tools", "parts carts"],
    safetyNotes: "Control fluids and protect open lines.",
    qcNotes: "Recovered parts sorted before release.",
  },
  {
    id: "station-module-removal",
    scenarioId: scenario.id,
    sequence: 4,
    name: "Engine / Alternator Coupled Module Removal",
    description: "Remove the engine and alternator as one intact coupled module.",
    ownerName: "Rigging Lead",
    plannedCycleMinutes: 0,
    plannedOperators: 2,
    plannedManHours: 0,
    taktStatus: "missing",
    bottleneckFlag: false,
    wipLimit: 1,
    area: "Heavy Mechanical",
    equipmentRequired: ["approved lift", "horizontal integration jig"],
    safetyNotes: "Do not split the engine and alternator in this station.",
    qcNotes: "Jig readiness confirmed before lift.",
  },
  {
    id: "station-tank-reorientation",
    scenarioId: scenario.id,
    sequence: 5,
    name: "Fuel Tank & Containment Tank Reorientation",
    description: "Rotate the fuel tank 180 degrees and prepare the containment package.",
    ownerName: "Hybrid Prep Lead",
    plannedCycleMinutes: 0,
    plannedOperators: 2,
    plannedManHours: 0,
    taktStatus: "missing",
    bottleneckFlag: false,
    wipLimit: 1,
    area: "Hybrid Prep",
    toolsRequired: ["torque wrench", "fuel hose kit", "inspection mirror"],
    safetyNotes: "Fuel may remain only if approved by safety and process conditions.",
    qcNotes: "Drain access, bend radius, no pinch points, and torque verified.",
  },
  {
    id: "station-panel-recovery",
    scenarioId: scenario.id,
    sequence: 6,
    name: "Panel Recovery, Rework & Service Parts",
    description: "Recover panels into reuse, rework, service parts, or QC hold paths.",
    ownerName: "Service Parts Lead",
    plannedCycleMinutes: 0,
    plannedOperators: 2,
    plannedManHours: 0,
    taktStatus: "missing",
    bottleneckFlag: false,
    wipLimit: 2,
    area: "Recovery",
    toolsRequired: ["panel racks", "cleaning kit", "labels"],
    safetyNotes: "No unused parts should be treated as scrap by default.",
    qcNotes: "Questionable parts route to QC hold/service parts review.",
  },
];

const tasks: Task[] = [
  {
    id: "task-verify-unit",
    scenarioId: scenario.id,
    stationId: "station-fluid-loto",
    rowType: "task",
    wbs: "1.1",
    name: "Verify unit, serial number, and traveler",
    description: "Confirm donor unit identity and traveler before teardown starts.",
    plannedStart: timeAt(0),
    plannedFinish: timeAt(15),
    plannedDurationMinutes: 15,
    plannedOperators: 1,
    plannedManHours: 0,
    status: "ready",
    percentComplete: 0,
    role: "Safety tech",
    skillLevel: "trained",
    dependencyIds: [],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: false,
    travelerSignoffRequired: true,
    reworkRisk: "low",
    customFields: { lotoRequired: true, materialStatus: "Ready" },
  },
  {
    id: "task-loto",
    scenarioId: scenario.id,
    stationId: "station-fluid-loto",
    rowType: "inspection",
    wbs: "1.2",
    name: "Perform LOTO and zero-energy check",
    description: "Lock out the unit and prove zero energy before downstream disconnects.",
    plannedStart: timeAt(15),
    plannedFinish: timeAt(45),
    plannedDurationMinutes: 30,
    plannedOperators: 1,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Safety tech",
    skillLevel: "certified",
    dependencyIds: ["task-verify-unit"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: true,
    travelerSignoffRequired: true,
    safetyNotes: "Required pass gate before electrical work.",
    reworkRisk: "low",
    customFields: { lotoRequired: true, qcGate: "Required" },
  },
  {
    id: "task-fluid-control",
    scenarioId: scenario.id,
    stationId: "station-fluid-loto",
    rowType: "task",
    wbs: "1.3",
    name: "Drain/control fluids, cap lines, clean spills",
    description: "Control fluids and cap open lines before release to electrical recovery.",
    plannedStart: timeAt(45),
    plannedFinish: timeAt(110),
    plannedDurationMinutes: 65,
    plannedOperators: 1,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Teardown tech",
    skillLevel: "trained",
    dependencyIds: ["task-loto"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: true,
    travelerSignoffRequired: true,
    safetyNotes: "Dispose or recover fluids per process.",
    reworkRisk: "medium",
    customFields: { fluidControlled: true, materialStatus: "Ready" },
  },
  {
    id: "task-photo-wiring",
    scenarioId: scenario.id,
    stationId: "station-electrical-recovery",
    rowType: "task",
    wbs: "2.1",
    name: "Photo-document wiring and routing",
    description: "Capture existing cabinet, terminal, and harness routing before disconnect.",
    plannedStart: timeAt(110),
    plannedFinish: timeAt(145),
    plannedDurationMinutes: 35,
    plannedOperators: 1,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Electrical tech",
    skillLevel: "trained",
    dependencyIds: ["task-fluid-control"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: false,
    travelerSignoffRequired: false,
    reworkRisk: "medium",
    customFields: { photoRequired: true, materialStatus: "Ready" },
  },
  {
    id: "task-label-disconnect",
    scenarioId: scenario.id,
    stationId: "station-electrical-recovery",
    rowType: "task",
    wbs: "2.2",
    name: "Label connectors and disconnect harnesses",
    description: "Label connectors, harnesses, and terminals before removal.",
    plannedStart: timeAt(145),
    plannedFinish: timeAt(230),
    plannedDurationMinutes: 85,
    plannedOperators: 2,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Electrical tech",
    skillLevel: "certified",
    dependencyIds: ["task-photo-wiring"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: false,
    travelerSignoffRequired: false,
    reworkRisk: "high",
    customFields: { serialNumberRequired: false, materialStatus: "Ready" },
  },
  {
    id: "task-remove-cabinet",
    scenarioId: scenario.id,
    stationId: "station-electrical-recovery",
    rowType: "task",
    wbs: "2.3",
    name: "Remove control cabinet and sort recovered components",
    description: "Remove cabinet, protect connectors, and route components to reuse/rework/service paths.",
    plannedStart: timeAt(230),
    plannedFinish: timeAt(315),
    plannedDurationMinutes: 85,
    plannedOperators: 2,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Electrical tech",
    skillLevel: "certified",
    dependencyIds: ["task-label-disconnect"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: true,
    travelerSignoffRequired: true,
    reworkRisk: "medium",
    manufacturingSteps: [
      {
        id: "step-remove-cabinet-1",
        sequence: 1,
        instruction: "Verify cabinet labels and photo record before loosening mounting hardware.",
        durationMinutes: 15,
        qualityCheck: "Labels visible in photos",
      },
      {
        id: "step-remove-cabinet-2",
        sequence: 2,
        instruction: "Remove cabinet mounting hardware and bag/tag hardware by location.",
        durationMinutes: 25,
        qualityCheck: "Hardware kit labeled",
      },
      {
        id: "step-remove-cabinet-3",
        sequence: 3,
        instruction: "Protect open connectors, remove cabinet from frame, and stage recovered components.",
        durationMinutes: 30,
        qualityCheck: "Connector protection installed",
      },
      {
        id: "step-remove-cabinet-4",
        sequence: 4,
        instruction: "Route recovered parts to hybrid reuse, rework, service parts, or QC hold.",
        durationMinutes: 15,
        qualityCheck: "Disposition captured",
      },
    ],
    partReferences: [
      {
        id: "part-control-cabinet-assy",
        partNumber: "SDG125-CTRL-CAB",
        description: "Recovered control cabinet assembly",
        quantity: 1,
        disposition: "Hybrid reuse",
      },
      {
        id: "part-cabinet-hardware-kit",
        partNumber: "SDG125-CAB-HW-KIT",
        description: "Bagged cabinet mounting hardware",
        quantity: 1,
        disposition: "Service Part",
      },
    ],
    customFields: { partDisposition: "Hybrid reuse", qcGate: "Required" },
  },
  {
    id: "task-cooling-document",
    scenarioId: scenario.id,
    stationId: "station-cooling-removal",
    rowType: "task",
    wbs: "3.1",
    name: "Document hose and bracket routing",
    description: "Photo-document routing before cooling and aftertreatment parts are removed.",
    plannedStart: timeAt(315),
    plannedFinish: timeAt(345),
    plannedDurationMinutes: 30,
    plannedOperators: 1,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Mechanical tech",
    skillLevel: "trained",
    dependencyIds: ["task-remove-cabinet"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: false,
    travelerSignoffRequired: false,
    reworkRisk: "low",
    customFields: { photoRequired: true, materialStatus: "Ready" },
  },
  {
    id: "task-remove-cooling",
    scenarioId: scenario.id,
    stationId: "station-cooling-removal",
    rowType: "task",
    wbs: "3.2",
    name: "Remove guards, shrouds, cooling package, and lines",
    description: "Remove bulky cooling support systems and cap open lines.",
    plannedStart: timeAt(345),
    plannedFinish: timeAt(475),
    plannedDurationMinutes: 130,
    plannedOperators: 2,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Mechanical tech",
    skillLevel: "trained",
    dependencyIds: ["task-cooling-document"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: false,
    travelerSignoffRequired: false,
    reworkRisk: "medium",
    customFields: { fluidControlled: true, materialStatus: "Ready" },
  },
  {
    id: "task-sort-cooling",
    scenarioId: scenario.id,
    stationId: "station-cooling-removal",
    rowType: "inspection",
    wbs: "3.3",
    name: "Sort recovered parts and release station",
    description: "Sort recovered components, clean the work area, and sign traveler.",
    plannedStart: timeAt(475),
    plannedFinish: timeAt(530),
    plannedDurationMinutes: 55,
    plannedOperators: 1,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Mechanical tech",
    skillLevel: "trained",
    dependencyIds: ["task-remove-cooling"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: true,
    travelerSignoffRequired: true,
    reworkRisk: "low",
    customFields: { qcGate: "Required", partDisposition: "Service Part" },
  },
  {
    id: "task-confirm-jig",
    scenarioId: scenario.id,
    stationId: "station-module-removal",
    rowType: "material_gate",
    wbs: "4.1",
    name: "Confirm prior disconnects and horizontal jig readiness",
    description: "Verify all prior disconnects are complete and the integration jig is ready.",
    plannedStart: timeAt(530),
    plannedFinish: timeAt(565),
    plannedDurationMinutes: 35,
    plannedOperators: 1,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Rigging lead",
    skillLevel: "certified",
    dependencyIds: ["task-sort-cooling"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: true,
    travelerSignoffRequired: true,
    equipmentRequired: ["horizontal integration jig"],
    reworkRisk: "medium",
    customFields: { fixtureId: "JIG-HYB-001", qcGate: "Required" },
  },
  {
    id: "task-lift-module",
    scenarioId: scenario.id,
    stationId: "station-module-removal",
    rowType: "task",
    wbs: "4.2",
    name: "Support, lift, and remove coupled engine/alternator module",
    description: "Lift from approved points and remove the coupled module without splitting it.",
    plannedStart: timeAt(565),
    plannedFinish: timeAt(675),
    plannedDurationMinutes: 110,
    plannedOperators: 2,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Rigging crew",
    skillLevel: "certified",
    dependencyIds: ["task-confirm-jig"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: false,
    travelerSignoffRequired: false,
    equipmentRequired: ["approved lift"],
    safetyNotes: "Do not split engine and alternator.",
    reworkRisk: "high",
    customFields: { craneRequired: true, fixtureId: "JIG-HYB-001" },
  },
  {
    id: "task-place-on-jig",
    scenarioId: scenario.id,
    stationId: "station-module-removal",
    rowType: "milestone",
    wbs: "4.3",
    name: "Place coupled module on jig and protect interfaces",
    description: "Place the intact module on the horizontal jig, protect interfaces, and release to integration.",
    plannedStart: timeAt(675),
    plannedFinish: timeAt(735),
    plannedDurationMinutes: 60,
    plannedOperators: 2,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Rigging crew",
    skillLevel: "certified",
    dependencyIds: ["task-lift-module"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: true,
    travelerSignoffRequired: true,
    reworkRisk: "medium",
    customFields: { travelerGate: "Required", fixtureId: "JIG-HYB-001" },
  },
  {
    id: "task-tank-photo",
    scenarioId: scenario.id,
    stationId: "station-tank-reorientation",
    rowType: "task",
    wbs: "5.1",
    name: "Verify fuel status and photograph original orientation",
    description: "Confirm fuel condition and document original containment package orientation.",
    plannedStart: timeAt(735),
    plannedFinish: timeAt(770),
    plannedDurationMinutes: 35,
    plannedOperators: 1,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Hybrid prep tech",
    skillLevel: "trained",
    dependencyIds: ["task-place-on-jig"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: false,
    travelerSignoffRequired: false,
    safetyNotes: "Fuel may remain only with approved process condition.",
    reworkRisk: "medium",
    customFields: { photoRequired: true, fluidControlled: true },
  },
  {
    id: "task-remove-base-hardware",
    scenarioId: scenario.id,
    stationId: "station-tank-reorientation",
    rowType: "task",
    wbs: "5.2",
    name: "Separate SDG125 base and remove 6 bolts / 2 nuts",
    description: "Separate the base from the containment tank and retain hardware.",
    plannedStart: timeAt(770),
    plannedFinish: timeAt(840),
    plannedDurationMinutes: 70,
    plannedOperators: 2,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Hybrid prep tech",
    skillLevel: "trained",
    dependencyIds: ["task-tank-photo"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: false,
    travelerSignoffRequired: false,
    reworkRisk: "medium",
    customFields: { boltCount: 6, nutCount: 2, materialStatus: "Ready" },
  },
  {
    id: "task-rotate-fuel-tank",
    scenarioId: scenario.id,
    stationId: "station-tank-reorientation",
    rowType: "task",
    wbs: "5.3",
    name: "Rotate fuel tank 180 degrees and install longer drain hose",
    description: "Rotate the tank against containment package and install the longer fuel drain hose.",
    plannedStart: timeAt(840),
    plannedFinish: timeAt(955),
    plannedDurationMinutes: 115,
    plannedOperators: 2,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Hybrid prep tech",
    skillLevel: "certified",
    dependencyIds: ["task-remove-base-hardware"],
    criticalPath: true,
    bottleneckFlag: true,
    qualityGate: false,
    travelerSignoffRequired: false,
    reworkRisk: "high",
    customFields: { materialStatus: "Ready", riskLevel: "High" },
  },
  {
    id: "task-tank-qc",
    scenarioId: scenario.id,
    stationId: "station-tank-reorientation",
    rowType: "inspection",
    wbs: "5.4",
    name: "Verify hose routing, torque hardware, and stage hybrid-ready",
    description: "Verify drain access, bend radius, no pinch points, torque, and traveler signoff.",
    plannedStart: timeAt(955),
    plannedFinish: timeAt(1035),
    plannedDurationMinutes: 80,
    plannedOperators: 1,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Hybrid prep lead",
    skillLevel: "certified",
    dependencyIds: ["task-rotate-fuel-tank"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: true,
    travelerSignoffRequired: true,
    qcChecklist: "Drain access, bend radius, no pinch points, hardware torque.",
    reworkRisk: "high",
    customFields: { torqueSpec: "Per hybrid build sheet", qcGate: "Required" },
  },
  {
    id: "task-panel-clean",
    scenarioId: scenario.id,
    stationId: "station-panel-recovery",
    rowType: "task",
    wbs: "6.1",
    name: "Clean, inspect, and label recovered panels",
    description: "Clean and label recovered panels before disposition decision.",
    plannedStart: timeAt(1035),
    plannedFinish: timeAt(1120),
    plannedDurationMinutes: 85,
    plannedOperators: 2,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Service parts tech",
    skillLevel: "trained",
    dependencyIds: ["task-tank-qc"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: false,
    travelerSignoffRequired: false,
    reworkRisk: "medium",
    customFields: { partDisposition: "Pending", materialStatus: "Ready" },
  },
  {
    id: "task-panel-disposition",
    scenarioId: scenario.id,
    stationId: "station-panel-recovery",
    rowType: "inspection",
    wbs: "6.2",
    name: "Route panels to reuse, rework, service parts, or QC hold",
    description: "Questionable panels route to QC hold or service parts review, not scrap by default.",
    plannedStart: timeAt(1120),
    plannedFinish: timeAt(1215),
    plannedDurationMinutes: 95,
    plannedOperators: 2,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Service parts lead",
    skillLevel: "trained",
    dependencyIds: ["task-panel-clean"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: true,
    travelerSignoffRequired: true,
    reworkRisk: "medium",
    customFields: { partDisposition: "QC Hold", qcGate: "Required" },
  },
  {
    id: "task-release-plan",
    scenarioId: scenario.id,
    stationId: "station-panel-recovery",
    rowType: "milestone",
    wbs: "6.3",
    name: "Line plan review gate",
    description: "Review takt, balance, bottleneck, and man-hour variance before release.",
    plannedStart: timeAt(1215),
    plannedFinish: timeAt(1230),
    plannedDurationMinutes: 15,
    plannedOperators: 1,
    plannedManHours: 0,
    status: "not_started",
    percentComplete: 0,
    role: "Manufacturing engineer",
    skillLevel: "expert",
    dependencyIds: ["task-panel-disposition"],
    criticalPath: true,
    bottleneckFlag: false,
    qualityGate: true,
    travelerSignoffRequired: true,
    reworkRisk: "low",
    customFields: { travelerGate: "Required", engineeringApproval: "Pending" },
  },
];

const processTasks: Task[] = stations.map((station, index) => {
  const stationTasks = tasks
    .filter((task) => task.stationId === station.id)
    .sort((a, b) => Date.parse(a.plannedStart) - Date.parse(b.plannedStart));
  const firstTask = stationTasks[0];
  const lastTask = stationTasks[stationTasks.length - 1];
  const plannedDurationMinutes = stationTasks.reduce((total, task) => total + task.plannedDurationMinutes, 0);
  const partReferences = stationTasks.flatMap((task) => task.partReferences ?? []);
  const customFields = Object.assign({}, ...stationTasks.map((task) => task.customFields));

  return {
    id: `process-${station.id}`,
    scenarioId: scenario.id,
    stationId: station.id,
    rowType: "task",
    wbs: String(station.sequence),
    name: station.name,
    description: station.description ?? firstTask?.description ?? "",
    plannedStart: firstTask?.plannedStart ?? timeAt(0),
    plannedFinish: lastTask?.plannedFinish ?? timeAt(plannedDurationMinutes),
    plannedDurationMinutes,
    plannedOperators: station.plannedOperators,
    plannedManHours: 0,
    status: index === 0 ? "ready" : "not_started",
    percentComplete: 0,
    ownerName: station.ownerName,
    role: station.ownerName,
    dependencyIds: index > 0 ? [`process-${stations[index - 1].id}`] : [],
    criticalPath: stationTasks.some((task) => task.criticalPath),
    bottleneckFlag: false,
    qualityGate: stationTasks.some((task) => task.qualityGate),
    travelerSignoffRequired: stationTasks.some((task) => task.travelerSignoffRequired),
    safetyNotes: station.safetyNotes,
    qcChecklist: station.qcNotes,
    manufacturingSteps: [],
    partReferences,
    customFields,
  };
});

const dependencies: Dependency[] = processTasks.flatMap((task) =>
  task.dependencyIds.map((predecessorTaskId, index) => ({
    id: `dep-${predecessorTaskId}-${task.id}-${index}`,
    predecessorTaskId,
    successorTaskId: task.id,
    type: "finish_to_start",
    constraintType: task.qualityGate ? "quality" : undefined,
  })),
);

const customColumns: CustomColumn[] = [
  {
    id: "col-loto-required",
    scenarioId: scenario.id,
    name: "LOTO Required",
    key: "lotoRequired",
    type: "checkbox",
    appliesTo: "task",
    required: false,
    visible: true,
    locked: false,
  },
  {
    id: "col-material-status",
    scenarioId: scenario.id,
    name: "Material Status",
    key: "materialStatus",
    type: "select",
    appliesTo: "task",
    required: false,
    options: ["Ready", "Short", "Backordered", "QC Hold"],
    visible: true,
    locked: false,
  },
  {
    id: "col-part-disposition",
    scenarioId: scenario.id,
    name: "Part Disposition",
    key: "partDisposition",
    type: "select",
    appliesTo: "task",
    required: false,
    options: ["Pending", "Hybrid reuse", "Hybrid rework", "Service Part", "QC Hold"],
    visible: true,
    locked: false,
  },
  {
    id: "col-fixture-id",
    scenarioId: scenario.id,
    name: "Fixture ID",
    key: "fixtureId",
    type: "text",
    appliesTo: "task",
    required: false,
    visible: true,
    locked: false,
  },
];

const zones: Zone[] = [];
const components: ManufacturingComponent[] = [];
const documentTypes: DocumentTypeCode[] = defaultDocumentTypeCodes.map((documentType, index) => ({
  id: `document-type-${documentType.code.toLowerCase()}`,
  productId: product.id,
  code: documentType.code,
  name: documentType.name,
  active: documentType.active,
  createdAt: product.createdAt,
  updatedAt: product.updatedAt,
}));

const calculated = applyCalculatedFields(product, stations, processTasks);

export const initialPlannerState: PlannerState = {
  product: calculated.product,
  scenario,
  stations: calculated.stations,
  zones,
  components,
  documentTypes,
  tasks: calculated.tasks,
  dependencies,
  actualEvents: [],
  customColumns,
};
