-- Task-level build animations (motion videos) generated by the SolidWorks add-in. Mirrors
-- step_exploded_views (task-level, authenticated per-project RLS, realtime) but for video: a dedicated
-- `task-videos` storage bucket with a larger size budget and video mime types.

create table if not exists task_videos (
  id text primary key default gen_random_uuid()::text,
  task_id text not null references tasks(id) on delete cascade,
  storage_path text not null,
  public_url text not null,
  thumbnail_url text,
  thumbnail_storage_path text,
  file_name text not null default 'Build animation',
  mime_type text,
  size_bytes bigint,
  duration_seconds double precision,
  width integer,
  height integer,
  caption text,
  solidworks_file_path text,
  captured_at timestamptz not null default now(),
  uploaded_by text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (size_bytes is null or size_bytes >= 0),
  check (duration_seconds is null or duration_seconds >= 0)
);

drop trigger if exists task_videos_set_updated_at on task_videos;
create trigger task_videos_set_updated_at
before update on task_videos
for each row execute function set_updated_at();

create index if not exists task_videos_task_id_idx on task_videos(task_id);
create index if not exists task_videos_deleted_at_idx on task_videos(deleted_at);
create unique index if not exists task_videos_storage_path_idx on task_videos(storage_path);

alter table task_videos enable row level security;

-- Authenticated, per-project RLS (mirrors step_exploded_views / step_photos): view => read, edit => write.
drop policy if exists "task_videos workspace read" on task_videos;
create policy "task_videos workspace read" on task_videos
for select to authenticated
using (public.has_project_access(public.task_project_id(task_id), 'view'::access_level));

drop policy if exists "task_videos workspace insert" on task_videos;
create policy "task_videos workspace insert" on task_videos
for insert to authenticated
with check (public.has_project_access(public.task_project_id(task_id), 'edit'::access_level));

drop policy if exists "task_videos workspace update" on task_videos;
create policy "task_videos workspace update" on task_videos
for update to authenticated
using (public.has_project_access(public.task_project_id(task_id), 'edit'::access_level))
with check (public.has_project_access(public.task_project_id(task_id), 'edit'::access_level));

drop policy if exists "task_videos workspace delete" on task_videos;
create policy "task_videos workspace delete" on task_videos
for delete to authenticated
using (public.has_project_access(public.task_project_id(task_id), 'edit'::access_level));

-- Realtime: full row on change + add to the publication.
do $$
begin
  execute 'alter table public.task_videos replica identity full';
  begin
    execute 'alter publication supabase_realtime add table public.task_videos';
  exception
    when duplicate_object then null;
    when undefined_object then null;
  end;
end $$;

-- Dedicated video bucket: 200 MB, MP4/WebM. Same workspace-scoped path scheme as step-photos.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'task-videos',
  'task-videos',
  true,
  209715200,
  array['video/mp4', 'video/webm']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "task video uploads" on storage.objects;
create policy "task video uploads"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'task-videos'
  and name like 'workspaces/%/projects/%'
  and (storage.foldername(name))[1] = 'workspaces'
  and (storage.foldername(name))[3] = 'projects'
  and public.project_workspace_id((storage.foldername(name))[4]) = (storage.foldername(name))[2]
  and public.has_workspace_role((storage.foldername(name))[2], array['owner', 'admin', 'editor']::workspace_role[])
);

drop policy if exists "task video reads" on storage.objects;
create policy "task video reads"
on storage.objects for select to authenticated
using (
  bucket_id = 'task-videos'
  and (
    name not like 'workspaces/%'
    or public.has_workspace_role((storage.foldername(name))[2], array['owner', 'admin', 'editor', 'viewer']::workspace_role[])
  )
);

drop policy if exists "task video deletes" on storage.objects;
create policy "task video deletes"
on storage.objects for delete to authenticated
using (
  bucket_id = 'task-videos'
  and (
    name not like 'workspaces/%'
    or public.has_workspace_role((storage.foldername(name))[2], array['owner', 'admin']::workspace_role[])
  )
);
